steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build production app
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
# deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--debug']
