steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build production app
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
# Use Default
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['use default']
  # Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']